// Auto-generated by scripts/generate-model-options.js.
// Run `npm run models:sync` after adding/removing files in assets/models.

export type ModelOption = {
  id: string;
  label: string;
  modelModule: number;
  mtlModule?: number;
};

export const MODEL_OPTIONS: ModelOption[] = [
  {
    id: "assassin-s-creed-glb",
    label: "Assassin's Creed.glb",
    modelModule: require("../../assets/models/Assassin's Creed.glb"),
  },
  {
    id: "city-obj",
    label: "city.obj",
    modelModule: require("../../assets/models/city.obj"),
  },
  {
    id: "hohenzollern-castle-glb",
    label: "Hohenzollern_Castle.glb",
    modelModule: require("../../assets/models/Hohenzollern_Castle.glb"),
  },
  {
    id: "model-glb",
    label: "model.glb",
    modelModule: require("../../assets/models/model.glb"),
  },
  {
    id: "valley-farming-in-southern-spain-obj",
    label: "Valley Farming in Southern Spain.obj",
    modelModule: require("../../assets/models/Valley Farming in Southern Spain.obj"),
  },
];
