/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext, ReactNode } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HZ3: THREE.Mesh
  }
  materials: {
    HZ3_Material_u1_v1: THREE.MeshPhysicalMaterial
  }
}

type ContextType = {
  HZ: React.FC<JSX.IntrinsicElements['mesh']>
}

const context = createContext<ContextType>(null!)
export function Instances({ children, ...props }: { children: ReactNode; [key: string]: any }) {
  const { nodes } = useGLTF('/Hohenzollern_Castle_optimized.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      HZ: nodes.HZ3,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.HZ />
    </group>
  )
}

useGLTF.preload('/Hohenzollern_Castle_optimized.glb')
